version: "3.8"

services:
  converter-service:
    build:
      context: ../converter
      dockerfile: Dockerfile
    container_name: converter-service
    ports:
      - "8000:8000"
    volumes:
      - ./files:/app/files
    environment:
      - OUTPUT_DIR=/app/files
      - ENCRYPTION_SERVICE_URL=http://encryption-service:8001/encrypt
    depends_on:
      - encryption-service
    networks:
      - app-network

  encryption-service:
    build:
      context: ../encryption
      dockerfile: Dockerfile
    container_name: encryption-service
    ports:
      - "8001:8001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  files:
    driver: local
